version: "3.9"

volumes:
  db:
    driver: local

services:
  db:
    container_name: db
    image: postgres:14.1-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: temp
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data

    labels:
      - "com.centurylinklabs.watchtower.enable=false"
